import type { Metadata } from "next";
import { Roboto_Slab  } from "next/font/google";
import "./globals.css";

const RobotoSlabFont = Roboto_Slab({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portforio site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-smooth">
      <body
        className={`${RobotoSlabFont.className}`}
      >
        {children}
      </body>
    </html>
  );
}
