import type { Metadata } from "next";
import { Roboto_Slab  } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";

const RobotoSlabFont = Roboto_Slab({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portforio site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

  return (
    <html lang="ja" className="scroll-smooth">
      <body className={`${RobotoSlabFont.className}`}>
        {children}
        {gaId && <GoogleAnalytics gaId={gaId} />}
      </body>
    </html>
  );
}
